blank_issues_enabled: false
contact_links:
  - name: Bug Triage
    url: https://github.com/Luc-Lwx/Luc.Lwx/issues?q=is%3Aopen+tag%3Abug+tag%3Atriage
    about: Please read this welcome message before creating an issue.